name: Update Kick Leaderboard

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  update-leaderboard:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies and Run fetch script
      run: |
        npm install puppeteer puppeteer-extra puppeteer-extra-plugin-stealth
        node fetch-leaderboard.js

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        if [ -f leaderboard.json ]; then
          git add leaderboard.json
          git commit -m "Update leaderboard data" || echo "No changes to commit"
          git push
        else
          echo "Error: leaderboard.json is missing. The Node.js fetch script failed."
          exit 1
        fi
        
          - name: Run Scrapers
        run: |
          node scraper.js        # מריץ את הקיקס הרגיל
          node sub_scraper.js    # מריץ בנפרד את הסאבים
